### ISSUE TITLE
add blogpost France week 1

### ISSUE THREAD

**Issue by janepie** [stormy-stories-surf/stormy-stories.surf#21]
Text draft done
part missing from Gitdev42

**Comment by mezorian** [comment]
Hi @janepie please continue this work on branch v0.1.0_21 ( https://github.com/stormy-stories-surf/stormy-stories.surf/tree/v0.1.0_21)

For this open your terminal, go into the directory to which you cloned this repo and switch the branch with the following command : 
`git checkout v0.1.0_21`
After this you can start working and commit all your changes to this branch. 
When your work is finished you can push to the branch v0.1.0_21 by 
`git push -u origin v0.1.0_21`

**Comment by mezorian** [comment]
By the way (@janepie, @Gitdev42 ): to make your changes feel more comfortable in the surrounding environment I moved them into the directory structure which is like in the other posts and renamed the .md file to content.md
