### ISSUE TITLE
add map to posts/2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore

### ISSUE THREAD

**Issue by mezorian** [stormy-stories-surf/stormy-stories.surf#47]
related to https://github.com/stormy-stories-surf/stormy-stories.surf/pull/43

**Comment by janepie** [comment]
Vorschlag: http://umap.openstreetmap.fr/de/map/brandon-bay-mullaghmore_372743
Da kann mensch noch viel mehr mit Farben und Symbolen rumspielen und Dinge unterbringen, cooles Tool. Kriegst du das in die Webseite gebaut?

**Comment by janepie** [comment]
in funktionierend: http://umap.openstreetmap.fr/de/map/brandon-bay-mullaghmore_372749
